[29] - Arreglar errores buyCoin
noemigportillo/laravel-docker-CryptoAPI-src pull request #31
Opened 2023-06-08 14:40 UTC by Davidalvarez55

He cambiado algunas cosas que faltaban y añadido el test en el controlador que comprueba el flujo completo de comprar una moneda. cualquier sugerencia es vienvenida

2023-06-09 14:01 UTC, noemigportillo commented on app/Application/BuyCoinService.php
> +        $coin = $this->apiCoinRepository->buySell($coin_id, $amount_usd);
En buySell en ApiCoinRepository en vez de realizar la llamada `$api->getCoinInfo($coinId)` 2 veces (una en la comparación y otra si no devuelve nulo) se puede simplemente asignar el valor devuelto a $this->coin y comprobar si su valor es nulo en el if. En caso de que no lo sea ya tendrás el valor que necesitas en la variable.

2023-06-09 14:04 UTC, noemigportillo commented on app/Application/BuyCoinService.php
>          }
La línea 50 es innecesaria. Ya se han recogido los coins de la cartera en la línea 47.

2023-06-09 14:23 UTC, noemigportillo commented on app/Infrastructure/Persistence/ApiCoinDataSource/ApiCoinRepository.php
>          $this->coin = $api->getCoinInfo($coinId);
Igual que antes, se puede ahorrar una llamada al getCoinInfo

2023-06-09 14:28 UTC, noemigportillo commented on tests/app/Infrastructure/Controller/BuyCoinControllerTest.php
> +        $wallet = new Wallet("userId", "wallet_id", $coins, 0);
Yo pondría user_id y wallet_id, mismo formato.

2023-06-09 14:34 UTC, noemigportillo commented on app/Infrastructure/Controllers/BuyCoinController.php
>              ], Response::HTTP_NOT_FOUND);
En la línea 22 el método buyCoinService->execute no devuelve nada, no se le puede asignar a la variable $coin. Es decir, en BuyCoinService.php se tiene el método public function execute(...): **void**

2023-06-09 14:43 UTC, noemigportillo requested changes
Sugerencias y apuntes en los cambios realizados. También hay algún apunte sobre lo que ya está en master.

2023-06-10 14:30 UTC, Tappedz commented
Muy importante que hagas pull de master en esta rama, sino tus commits no van a pasar la integración continua.

2023-06-10 16:22 UTC, Davidalvarez55 commented
se han realizado los cambios que se han pedido por parte de los compañeros, incluyendo entre estos eliminar lineas duplicadas, simplificar partes de codigo y renombrar algunas clases para hacerlas mas sencilla de entender.

2023-06-10 18:20 UTC, noemigportillo commented
No tengo nada que añadiir, lo mergeo

2023-06-10 18:20 UTC, merged